export declare const BaseColors: {
    Blue: string;
    Red: string;
    Green: string;
    Purple: string;
    Cyan: string;
    Orange: string;
    "Light Blue": string;
    Lilac: string;
    "Light Green": string;
    Brown: string;
    Black: string;
    Gray: string;
    Pink: string;
    "Dark Blue": string;
};
export declare const AdditionalColors: {
    "Indian Red": string;
    "Green 2": string;
    "Green 3": string;
    "Dark Turquoise": string;
    "Dark Violet": string;
    "Pink 2": string;
};
export declare const ColorPaletteArray: string[];
declare const ColorPalette: {
    "Indian Red": string;
    "Green 2": string;
    "Green 3": string;
    "Dark Turquoise": string;
    "Dark Violet": string;
    "Pink 2": string;
    Blue: string;
    Red: string;
    Green: string;
    Purple: string;
    Cyan: string;
    Orange: string;
    "Light Blue": string;
    Lilac: string;
    "Light Green": string;
    Brown: string;
    Black: string;
    Gray: string;
    Pink: string;
    "Dark Blue": string;
};
export default ColorPalette;
